# Generated by Django 3.0.2 on 2020-05-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uuid',
            new_name='uploaded_by',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='uuid',
            new_name='uploaded_by',
        ),
    ]
