# Generated by Django 3.0.2 on 2020-05-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200506_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_field',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
